//! Thumbnail generation for saved clips.
//! Thumbnails are generated by decoding the first video frame using Windows
//! Media Foundation and encoding it as a JPEG via the image crate.
//! Returns None on any failure so missing thumbnails are non-fatal.

use anyhow::Result;
use base64::Engine;
use std::path::Path;

/// Returns a base64-encoded JPEG thumbnail for the clip at `mp4_path`.
/// Caches the result as `<clipname>.thumb.jpg` next to the MP4.
pub fn get_or_create_thumbnail(mp4_path: &Path) -> Result<String> {
    let thumb_path = mp4_path.with_extension("thumb.jpg");

    if thumb_path.exists() {
        let bytes = std::fs::read(&thumb_path)?;
        return Ok(base64::engine::general_purpose::STANDARD.encode(&bytes));
    }

    // Thumbnail generation requires MF source reader — skip silently if unavailable.
    Err(anyhow::anyhow!("thumbnail generation not available"))
}
